denis-jullien/leafy-ils

- .gitignore
- design/project_description.md
> add project description

- README.md
- design/database_details.md
- design/tools_selection.md
> add few files related to the design

- .github/workflows/python-app.yml
- .vscode/settings.json
- design/python_design.md
> add static analysis through a CI

- .gitignore
- .vscode/tasks.json
- backend/database.py
- backend/main.py
- backend/models.py
- backend/routers/book.py
> add apis to manipulate a book

- .vscode/tasks.json
- backend/main.py
- backend/models.py
- backend/routers/family.py
- backend/routers/member.py
- design/python_design.md
> add apis to manipulate a family and its members

- .github/workflows/python-app.yml
- .vscode/tasks.json
- backend/main.py
- backend/models.py
- backend/routers/book.py
- backend/routers/circulation.py
- backend/routers/family.py
- backend/routers/member.py
- design/database_details.md
- design/python_design.md
> add apis to manipulate a borrow history

- .github/workflows/python-app.yml
- .gitignore
- backend/main.py
- backend/models.py
- backend/routers/book.py
- backend/routers/circulation.py
- backend/routers/family.py
- backend/routers/member.py
- backend/unit_tests/conftest.py
- backend/unit_tests/test_book_create.py
- backend/unit_tests/test_book_delete.py
- backend/unit_tests/test_book_read_all.py
- backend/unit_tests/test_book_read_one.py
- backend/unit_tests/test_book_update.py
- backend/unit_tests/tools.py
> add unit tests for book CRUD

- backend/main.py
- backend/models.py
- backend/routers/book.py
- backend/routers/circulation.py
- backend/routers/family.py
- backend/routers/member.py
- backend/unit_tests/test_book_create.py
- backend/unit_tests/test_book_delete.py
- backend/unit_tests/test_book_read_all.py
- backend/unit_tests/test_book_read_one.py
- backend/unit_tests/test_book_update.py
- backend/unit_tests/tools.py
> fix python import

- backend/internals/book_notice.py
- backend/main.py
- backend/models.py
- backend/routers/book.py
- backend/unit_tests/test_book_create.py
- backend/unit_tests/test_book_delete.py
- backend/unit_tests/test_book_read_all.py
- backend/unit_tests/test_book_read_one.py
- backend/unit_tests/test_book_update.py
- backend/unit_tests/tools.py
- backend/users.py
- design/database_details.md
- requirements.txt
Include already developped functions in /app : 
authentification with fastapi-users 
Book notice query from Google books & sudoc
#31
> Add app function

- README.md
- backend/models.py
- backend/unit_tests/test_book_read_one.py
- backend/unit_tests/test_book_update.py
- backend/unit_tests/test_family_create.py
- backend/unit_tests/test_family_delete.py
- backend/unit_tests/test_family_read_all.py
- backend/unit_tests/test_family_read_one.py
- backend/unit_tests/test_family_update.py
- backend/unit_tests/test_member_create.py
- backend/unit_tests/test_member_delete.py
- backend/unit_tests/test_member_read_all.py
- backend/unit_tests/test_member_read_one.py
- backend/unit_tests/test_member_update.py
> add unit tests for apis that manipulate a family and its member

- backend/main.py
- backend/unit_tests/test_circulation_create.py
- backend/unit_tests/test_circulation_delete.py
- backend/unit_tests/test_circulation_read_all.py
- backend/unit_tests/test_circulation_read_one.py
- backend/unit_tests/test_circulation_update.py
- backend/unit_tests/test_member_create.py
> add unit tests for apis that manipulate a borrow history

- backend/routers/book.py
- backend/routers/circulation.py
- backend/routers/family.py
- backend/routers/member.py
- backend/unit_tests/test_book_delete.py
- backend/unit_tests/test_circulation_delete.py
- backend/unit_tests/test_family_delete.py
- backend/unit_tests/test_member_delete.py
- design/api_design.md
> update delete API to return 204 no content

- backend/routers/book.py
- backend/routers/circulation.py
- backend/routers/family.py
- backend/routers/member.py
- backend/unit_tests/test_book_read_all.py
- backend/unit_tests/test_circulation_read_all.py
- backend/unit_tests/test_family_read_all.py
- backend/unit_tests/test_member_read_all.py
- design/api_design.md
> update search API according to the api_design: page and limit parameters

- backend/routers/circulation.py
- backend/unit_tests/test_circulation_read_all.py
> manage PaginationMetadata for circulation SQL table

- backend/routers/member.py
- backend/unit_tests/test_member_read_all.py
> manage PaginationMetadata for member SQL table

- backend/routers/family.py
- backend/unit_tests/test_book_read_all.py
- backend/unit_tests/test_family_read_all.py
> manage PaginationMetadata for family SQL table

- backend/internals/constants.py
- backend/internals/table_management.py
- backend/routers/book.py
- backend/routers/circulation.py
- backend/routers/family.py
- backend/routers/member.py
> factorize the paginate metadata saving

- backend/routers/book.py
- backend/unit_tests/test_book_read_all.py
> add book research by available

- backend/internals/constants.py
- backend/routers/circulation.py
- backend/unit_tests/test_book_read_all.py
- backend/unit_tests/test_circulation_read_all.py
> add circulation research by borrowed_date

- backend/routers/circulation.py
- backend/unit_tests/test_circulation_read_all.py
- design/api_design.md
> update design to include common format for query

- backend/models.py
- backend/unit_tests/test_family_create.py
- backend/unit_tests/test_family_update.py
> add last_adhesion_date field to a family and enable the constraint about email and phone_number

- backend/routers/book.py
- backend/unit_tests/test_book_read_all.py
> add book research by archived following filter query design
